---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: macro-service-secret
  namespace: nutritrack
spec:
  encryptedData:
    DATABASE_URL: AgBHIK7rbGoATGnOMFhusWHugTlxTGlAQValloGKpZQwyJC7WKWv8IBjKRDkysmDYvJNezcaqyYiasmbr/dhtlM5fZrQDU7vXWraHpLfDMpoQB+tgmYU6qLSc+rBtfq>
    JWT_SECRET: AgA+4HNyodBU+rJTf7h3UbB97iXpMg7OjSpw4mtjXmokhdH1JvSvB3+OHpXdPZljNxYx7I91ppO6W2qyJ2dF/5qhhpuBFphR13NjjRZmDtLqoP95BCCeJyq26awzvnKfz>
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: macro-service
      name: macro-service-secret
      namespace: nutritrack
    type: Opaque