---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: macro-service-secret
  namespace: nutritrack
spec:
  encryptedData:
    DATABASE_URL: AgBWUH4k19VoKHvkQnyWIgsxxivmOm2janYolsdJtLPnOvAguyP+DIunZrxIjTQpur6yyO3DpEvF9+PeFd8kdMJzHCjK6k0m2uxsjGgFyOiQNjiQNGhKYwC96B1dsUFa0PaZ/Kvoxny6AkpJSR+IuyxcHZD5/RPYvh16sZk+QXp0FXyry2u75FqvzxX80ZQ0cnUlaLKDOTK8TMkf4y5neb71cOpyndXTcobk6LnSkiKhKphb0bXy13Yb3Dao45/W/kaCXMO62ZWvdSe08jAE8576G7ewbn9KC1O2di+UtoISxq5P2fRuVCFtGYLQOyZ/cg9WZxOBWw9gavJ3jX8TfarRTt3dwb9lCHaz9ZRuMGfQb2FEwt5VJ20/x1aIpkrQbnqVZkGjGh4cblFjN+T69eAg1Uxjog25BnGIIM3sKNriuAQG/7q0UAT5EACSTpcHB2PzsWSaBbjg8tGLEGoTSqitUo25a7k2bvyQETlyTLAAZaYSxMF638/03oHubmMqVrRpDTNWlBpAzwKLXOqC+BzdI0UxmzHA7/ig9ygE2H+gvxcxoDkjgV9unuyHZ59Ck93hOTRDCMPd5YJCkOIU7+MSUBCQHdKhHKbTq0ImgL+y1L8OF4pv+6c6U0Rjm+tUckdpJFgiY8P3e8TbitUUluzK4IR72s0LR2dyvnS6pJlLQJA6s/PODziv67VDwaAWVDpaI8ltoTln4x3/98lCQ0NVuGYCcRJNsVSMLieGgNfFGrwBbQWWSEPBFqw0EaKP4RxpfhB9rA++Qn4Oe4pFxXsbc3YXj/6qozBMMAwAyqDB7ExOO/gosfw9n4ePodNhmyL3yghSwoAAtpAxz882Cyhk7tLRtspn//T7MkM=
    JWT_SECRET: AgAAx6GlK/VHj5Cf5qzupg42wIEJHdl+Oq9siU6VgimLzqm1DoHKs0mAfDZhc24A/hBsYbD9FmIgi4x/VEkl8fwavDOU7RMOUN66AFMoakfUB9AHV1rbLJf/iiPl9vs8O+iEPduOvsDBiSDr3oO5a0bRIFtkHRgNQzozfzSvy15EHfnLdh/mnaM/SRZJnPJali67DawBaIINJ8Ye7CJlAB2MsBLf/z9Mp3vDOIO5JZ6E/t1EDv/fhCVAdWrVQpE7GwwkR3GGcnu3XFMJLuE0TLf0jVsTwgKAyUQlYRU/N6Yf6BlVYOzS9lzaAB6Gqf7q7Gol4hDcdch9eHsu8HU6XOuzCOA81e4QDqa5rYMoITZXbwY7m3FzWgQLNIXnYzxqwxzwGavGcCs6taJzkSFg2iI+VcvuKuABeCAoPhXwC8fwI89rLxL9eJrKLGa2MwfVcytOwPIeChz2olaNAcYWXxWMmEwMfAKguYMUfspfcdsvR/34HT2epVuVrQBEShf5RRn3ZmX+KLfyJNrqbVShD0PL9AvSjo8zMx57k1X4h1q0RlAotKWJMkCtMx3VBtR6uV43LA/gADRRvRienYy8nW3TQqkHZOCjFV8gga7ys6H3+lWtuoWOgKjeocsOL832TehW37+OMeaRWNTlA7aYasjlbZI9e5iSIvAC+Wl08YaaUifu8zi83JU/mOC+F7X6cKbwFzlGjxLwC0uUcLjobY8sbRvlvZsLH4aidjkUzEL2etnl4zMKSaun
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: macro-service
      name: macro-service-secret
      namespace: nutritrack
    type: Opaque
