---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: macro-service-secret
  namespace: nutritrack
spec:
  encryptedData:
    DATABASE_URL: AgBHIK7rbGoATGnOMFhusWHugTlxTGlAQValloGKpZQwyJC7WKWv8IBjKRDkysmDYvJNezcaqyYiasmbr/dhtlM5fZrQDU7vXWraHpLfDMpoQB+tgmYU6qLSc+rBtfqlbaz7peayA5lUD03ZWFMPTZNT8qMIqwrxWK1mG8ty9U+tXIOSyNFIcd/YT3XK2qn0KXAqHeNdfMBOpCGRXcKt7lLmngrpnwAMWBXSXJn1s1TJYPr8DcsQgM/a3IE5Lci8ovpX4Q29zVJC8FsmAb0qP0WEUz4NConspVYzr57xdTXIcsXTTFDKP/speZAcOTGTwD0mZO3Munfg74a4PW2sceiSYSIeDY89yEASJcm0cWQw2NvWn8MlUlT3Ft7zsABt4KWcDgKk3RX3472s6N6A6UHchuzefHLgfP5nhdKFgBDSXK2U7PkxTSlEsKOc2ci7cfUXnKsie0tZQBwmoviHdFkIMe1DD+zP986EueBLdrkrNPgkYknANglC4GsJsqqK+d1WdwVpSJZd+LXLGTaWqvnbTp+bVjqotHN7rlwHciGjeVDuOt8c8SmgiG/rupsWOpVsPoKN33cJvrbzRbShhBDsyF4TZt70gWxiOtObd5HIjf5t/kt2++oFz0IJy9G19LY90+WCcprqQcpU8z+VXdr0mgHQme0NdlqaNUbw3SZEMHk6fz41YYdU+iALxfwqOx2QKA2mx3+pLFH605BNFZyqcXxM7wPbiBwfH91UHJUBMRRsHEFUanHCGIlRJv5/YKcWlrcI+Ds0FDzo54wBySZb3Zqbj6I/wLcyyNq8HNE+r7mYIEcqRueqyTdtDOoWUQ9f/53UY+4JCiTVSpkOiM/93Sh1U7c5IQ1+zUg=
    JWT_SECRET: AgA+4HNyodBU+rJTf7h3UbB97iXpMg7OjSpw4mtjXmokhdH1JvSvB3+OHpXdPZljNxYx7I91ppO6W2qyJ2dF/5qhhpuBFphR13NjjRZmDtLqoP95BCCeJyq26awzvnKfzqONx7vC7VuzTpBuilEs6QVzyvd0Dy6+dndj5ZocXh+x530qN4pZgAxhide85R0w4ql7k3sPqNYWPa+/Qb9JPjWtYVAyX3x0l2nqyaGZUZDnNqpdgM+rnwqpVHK+3v7q2OjlKRXnyLU0OELsJvtQB9Co93wMi6gsGCnicMEoHjraFWPk0YvdDfplbSeU2O6nyeDa4anY7Fepa+K3tE0ngOEKu6BrCj+s38f/GbTFVhZ/75P7cmvxBtLb5w/yFhGcuK33FUUcBETE1YXxSliQ+i+OUjLHHajlAkefYWrqsJOIRpd6/IiMcZpBPayWDf0qjFSzt8qS3SDvcnsWsYKdMHiez8KwxhOTXOHrayfek1baXL3RPAM2tMdBl5OMI+QnZ/SzguQFys8VPfYkEuBUCH4v/09lXtLnxWesPOyyHvlN3bN76/2lgCb3jUdS4OfPhPjnV0NmogRASVTXoxT3n/4QBypiuXbczyL2E2Zbp/KAspcyNWPxOmMZ+BWTPTF5tydXDZZZCsgFeOaQqESZDIH6MGyV6ThXU1dNrUm7uX7nfC1qenWX22s9DUrWinR21mobNRRhHGi/2BM1Wyc+RJoJxH/YR1EUdbNhne+CZgCrQysR3vKK/OHwZp+HCHSjAmHpjcM=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: macro-service
      name: macro-service-secret
      namespace: nutritrack
    type: Opaque