---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: food-service-secret
  namespace: nutritrack
spec:
  encryptedData:
    DATABASE_URL: AgBaGWMtWDLotWluW1Y07HQpZ6zmLtLhPQJeMDqa73E+8TExvJQIMhSn12iZszU8VeOATnJetWeT7JFMwKrL0pslp0S+YHObrKb5R/CdG0Wwf5rvoNOSO8a0gWoLDMon9xYyW7+f9eFw+tkzfFKO+CYsKx771yYtrtfAZP5LHL0FNa8/dASYHVS0K+A9U6+GMXkTaaM9oMHpjZ/ulWCwMSvuHM9z4OAKDhjY8+YnjimHcO3V21+xNHaTmymEootrSma2xFJob2aEPK7TKLUHCua5tBcLBAcLSoooB/kHm3Am58G2FQIoISI+HBUiEdcnqDIkzEsX5RwGP7lV/dV2xTF2nN3nzvRHh/V2Tm18mHs0loF+ikCP2KRSH50VVCTxeahPNSSXro8lYPvuUIwpSXFGDMlATY/uOA9rZDghIeBKaW3+rKWnxsekK57ccop/SopcR+FjT1oYqPePGx32hQ9anQexLEaJeMwJ6BGmJf04RmIH17ac5eWSI1bYiBRfbZUz/9TFeewflc2pbOLHS2k1bpuRjvvh3oQHUhti8gMwXQLPGduyWfgOH+F9KcUsAcQVG7ydntj8S9fhD6WbJf+6UWyneWN6eh70x6Cxz2vQeaZ00vvPtBt/QDmBLuG3QvyAKaVRKpT+DPF86aEsBxLPpY4KRLLKrkfmU1bw5HyYTJYwDtqtas1BWxiGPccCx8bmY69n85cbnRTu0O5f1wVx2Lkt9cLoT6RZzb1Y1Zn9SaNGg369ViXYxws4mMjjfOvPX9emOwc7SAI0hSsLDVA3O7xB/pXkeZVMVdneR6DREpf3+o/kPqVetAwj6euaDUdZ60xuWQLpOebGRYfYRBnWqui/Z5cNtQk=
    JWT_SECRET: AgAo+UYiidjMJFh4yO8JckhKvav/U09Vlinu7FUlCumJq+bKlWG0lKiP4fQMblHmGY0xyQfxmPuFoxzSrPFlAdshMSaXqR3dlSRtX5dRQqMZOpN2IXrBZvapdVIf2wszgmJdQSyxJ1BSjfuz1KKhtsRJF78MjCPdpUCExYM7T4iIeSWxG2BBh/CGfOkwKzjTno+jxLXdlt2b4sSaEY3IyQ6WhTDr6Ns1VKRX8ojhFaL4RbZM3zmPiTBhMlxFd+UJWPI30dysqYRqlc57soh7JO1514YUzPIrf+vp1CW4N4oVjpojBX94rcUZH0vzSXMFrx5YWP0QNdpQ4thvluoO4La9Wk/ZjFQAZ3JqOWWrlYexbjSyWw/F//XOEFyta7lflQdTFua9JF28T6dVLC4zeZSbnF+gw1+nU46VFXREsrrk7fit+/zfeppCr8MW9W5PtxaNEisqC5HEibXl8up0vMpB1CcjD3JoTpsXDtV9imuFy10Iw9DbYGNjVh5PEm2Xwy3TGzLmlvlyXpT6J08mGnVDhCxi2fg57JxjZrFQKZFPhNfKwZuRcL3w02/1TdNrBk6zXYhLXmnsSbVbtwGpIFT8U3SZvZi2eplIs6ZrhMZG3FMAxOBUTn/ksskVIirX0eytiT+UkhQvMOX8WQ7VgObKNOpzfYp7Uj3PPu/PntUHgoHLHhU5lOQ/kqY7BbfstPt4itIqqr5CiUiXvsqv7KpqlTw0RIleZUpGXSyGZSr2WfZytJmJrbYUef25B2EJwzqDFgA=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: food-service
      name: food-service-secret
      namespace: nutritrack
    type: Opaque