---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: food-service-secret
  namespace: nutritrack
spec:
  encryptedData:
    DATABASE_URL: AgBaGWMtWDLotWluW1Y07HQpZ6zmLtLhPQJeMDqa73E+8TExvJQIMhSn12iZszU8VeOATnJetWeT7JFMwKrL0pslp0S+YHObrKb5R/CdG0Wwf5rvoNOSO8a0gWoLDMo>
    JWT_SECRET: AgAo+UYiidjMJFh4yO8JckhKvav/U09Vlinu7FUlCumJq+bKlWG0lKiP4fQMblHmGY0xyQfxmPuFoxzSrPFlAdshMSaXqR3dlSRtX5dRQqMZOpN2IXrBZvapdVIf2wszg>
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: food-service
      name: food-service-secret
      namespace: nutritrack
    type: Opaque