---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: food-service-secret
  namespace: nutritrack
spec:
  encryptedData:
    DATABASE_URL: AgCc++pHZgiXErIM9MlDdbY+lULv16RaIxU3J/u/dviTTcI2NaJtg8/4iOBEZ/pqUvIZuOjqj+Nvds/T29AaKDm6KGIK4uT5EgKEFSkpuhc3tcpmY0x+ITGJSGFsHvJhYLeb7HIa+chWc1ZA55dPUGRVAiWXri8p+qFo6R8lO4oDY3wHWO8w7k4tat6WESEoo0eJtJxtwE5TGk08kvZCMKaRidoC4x5ViffohCFPgcUCrm92/KUtRp+dyQ6+OGG//dTBuE9vIuMgu9hBFjO9NtKeGV9o9Cm6/053ostgsGZh3AsbOngtAAN7PhM/+6q+por/otKslCEYwGONYgRwOkGRwcSkDxMi7iMQB0OisIoSAvrFhGxHWhNwJNLuxFy22e/ajCeQZbek9RxXUQtWXyGfwq9glxhUh48gZfDcF/jFHVGSvCjBM8N24iv0yKhI02roOoXTa9fx0S5xw5o0RoFz8Q/w+V8D2JDf2RHXiQeDRyg/ppBHJeRpqqXof697vp2m8bi1FdZLs2fUyHW9LvlOI3qFhsQOuNMx171TNw4lDH0gJffx4/mD5mnWZ4HOP1SpVDMQm2091HQMzocEQXmUbPV7FweizlVaH7deLjxxwXrQ+vPzue7Zdqo/N1B/24Yjhrp64VwHP1YCAYQikagLGZdark52VuW9Jhz7VsqnZ/CNLx4L3jYWlAkJfzBJZLwPmxULcFdsPNs03x+EAz9yIMWEw+WvnzAUeK65qzYjQp/N278JgirkR0SHvEC5S7rE5+psU8nlfvslmJhnBryQlWCVVphqW+qK9I4b8GKeMQ5uo4+QYMClpEHgdutDsiEr9Qd6SsUymKlc2LaTNzaW3V1s4ipVcLU=
    JWT_SECRET: AgAk+FGo+Mx6Q+iFe4SrqUThDdZjq1WScqynW5McSAXkZXzyiDY+/KA06qyd1GGkTecV/QCpO27Ny/MsliO0hWSknbyYjINL4rbdOFRGcCqwLlJPOad9xrynPSz90lx9Zh/IozQtsgT85UDAzC3oW/iucPh62nvor8i3AsPSSWnoaCqvHqJhmctwbh+S9zWkaFSoKDjl1Mf3F2ecDxosYbSlCOIp8yPPbyW+3oQ038QzvZSoyzfbudMqGKyDg1KNIvgjj1TwVMeS6bmf12VztJH17hiXlecDQWLilGFkOM9qLtp9iixQo8sqPgJWot/ywW/VF8fnwMSUjmLP3mWQeZNQiwF2i7tm8LrnHWiy+ZQGJ8E6/MNdJRciuG1uO10MXIyffEqP9ed670+ynkn5giwqzJSAlqYBi4lMpdUd3XeQ4l4hwqG3m6ax94J8dtSo3fLGawTex6iyf5wCf8vkbf2ksKLMq/yJFMKUqEKNKQE1HIHfJmx5OILV2Bohab0cLHIqVsdOlQLhNcn4j+nvI2z2tKd6MVMFyveq1MeB85v1e0gC5txRKnJd4KmybfqAhpkcBTrTyGbqXIomfRmI8uW3cfxVrV4NOxJ6gGVlpdaac+Cg7iWjDxbenV1dhaXYUn5zKwqRH9w1J3mNgigenynkVOc/TkI3loZ3rdrISKpU5W/MJKgAKil6ivMWqXcjrv5ag386R7SLluwOO0LvGYgDV9iaOCmHCQUK8s+nijIvfJZ2ZoQ+xVVQ
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: food-service
      name: food-service-secret
      namespace: nutritrack
    type: Opaque
