apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nutritrack-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: nutritrack
  source:
    repoURL: https://github.com/Nutri-Track/nutritrack-charts.git
    targetRevision: develop
    path: infrastructure/envoy-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: nutritrack-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
