apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nutritrack-keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: nutritrack
  source:
    repoURL: https://github.com/Nutri-Track/nutritrack-charts.git
    targetRevision: develop
    path: infrastructure/keycloak
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
