---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgDDXXWkg4i/R5LM4vA9biwZCqGmM4xjDfIBZqsdpnAKeuUUGlX935CXk2M4+eKSIZaqAix5DUl+RIHnxb6wEtHk7hKeFhkymdFFasfKekUCsnAPE2YcCtpq0HmwPFDYIobILrZgwKPWUsNNO2Fn+3RcFSW0jZjxdzU18/I7/nxFh7eKXv4ZOmOIwP/GDgKkjBLjYIIfHGuhWYlNYPDW5c8rhN/MOsLKyhqFmJkqbeWtVMgtLv1nD3WXbEHuKRk85gHhR0O5Mg74TSGoQm0N2yOcccD8UX+Rr6D6yOBnvuzGAzsVSj3qeEe0nSGJ/SgSEu8vADgbSneWZxCCsGOD4fn4OelmTc1a/wwKbVA+UqsO4VkYm3Vxsf6m+MFprRJ8z3iIirrR0iQOpEchmJhOEh8pHwEhofcIyxT77KAQFMMvWkkHt99h25vvaaxf0w5KjsdcEc+vEOxk3SI3+CkRIPpDVB2mty8GTyCwqPJSw1+PuQVoiXJpD9wC5Z3xRDymA9khQv0J4dJYS3FbnJv+6EuK2pmTneWsOJBqbrl1xX8VlLMheFcZMAABhcYHtTaomNAnVT+hpNFdCuJ2KZR2pm4ggJOeMvA7W4laHnQaeWuLgPWk5sz5b57io0OG84Bss5Lwe7N5F5I3H2wBhU95K3Y935hHPK6UQOcYiRXd17vm83kPVtJo1mMueIpueD2D0pQsOrg2BhrDFGaRqHEzoOg8U9b3X0uiPBW807OVCYpW7cvRTQ7VmHjtsqGy9D+V+mYVrYA0X9mmtLzXTrJFe9vgHNTqScu/2OBc9L1cV1xsN9w=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: monitoring