apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: {{ .Values.global.namespace }}
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/part-of: nutritrack
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://nutritrack-loki.monitoring.svc.cluster.local:3100
        access: proxy
        isDefault: false
        jsonData:
          maxLines: 1000
