apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  namespace: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headlamp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: headlamp
    spec:
      serviceAccountName: headlamp
      containers:
        - name: headlamp
          image: ghcr.io/headlamp-k8s/headlamp:v0.25.0
          args:
            - "-in-cluster"

            # OIDC Integration!
            - "-oidc-client-id=headlamp"
            - "-oidc-client-secret=$(OIDC_CLIENT_SECRET)"
            # This points exactly to the Realm created by the Operator
            - "-oidc-idp-issuer-url=https://keycloak.dev.nutritrack360.in/realms/nutritrack"
            - "-oidc-scopes=openid,profile,email"
          env:
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: headlamp-oidc-secret
                  key: clientSecret
          ports:
            - containerPort: 4466
          readinessProbe:
            httpGet:
              path: /
              port: 4466
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4466
            initialDelaySeconds: 20
