---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: headlamp-oidc-secret
  namespace: headlamp
spec:
  encryptedData:
    clientID: AgAUAhJVIVaxbakHZ26yFdSj5XKPGj6UaseVLr96NU6//U7SXawc5dix8Gtf9LdZi757QRkcrT92gKStYCQUEVO2ivN1MKKZeEENAr6DHM7pVuKg4g9skOG0HCsHNZQplfxereBxVpyA8/HLMlhekUvF8GCEGrFiKfC1BQXuGI0cFksUWRJ1zTXDRnRDRvSyThy6kM6N4zKp4Y8yC42g6oLyrslhfXqWxs/j7yQjd/m2GR3dnaIaahNDU9gV5IxROjHoMEZahbJG7jenqB5hgJRboDKd9bnyJ/kpAgaiRQ9qDuVyl251GDcBIpfFtD1awZM7j2nwHGNn6sZQC3O2xHYPdQahMDyDvavg9Jp7Hiq1Rs9tx6O9Vry2tfsZfhXuffFEYcH5zikQqose2I4fnI3so+XKSLRllsCwnuL77mtIXLq6BETksVviRkf399uw6SQbJjMgYoy8T4tGHivk70Awyd6RDO786dC9gZAGlcIQYmHJiGs5nhReyn7ZqdsJxdkHV0GbvEnHSepKui9IHqN43CjFvlmvb6T5pVega+Gbs9uGxVm4jDvWSBNu70TVAmgTbErhtZBQGo5IAJ4BV5t3YeUuQ4b6WGOnQqGjqX5cQwQ+5hyoK8+zZ1HcksTXiDhB9Kjyug/fR3iXLsBcK8CdKN0r1fjef6lXo8eZ0ujJsSZU4RzMwOR8A9Gbx/xaNoyzum7xMCuiBg==
    clientSecret: AgAHQSCcnTj9SEI/G7yqfk+AF4IPKYI6HXpu5M1BuFWWZTeoWPs76k3XaYZs7Wz2WIgFAFiQxsLTgMOi/8Ml8XUHSzS5hUYZpxaDNpyEKdi/xk1Sd16VQ3Pwm/vQRMj1awFrQEttATxcd76mHXIROFbohd5UfiE4AvdZW74jCECpNvl0b7A85TnwieW85FTaIKpxZT5qSPvuVFjw/DjneDAM+ZpbaDleTEnSiKsCkDvP6DDNmw+/eJ8p9oEY7eXjrhGaVlOd/GtiV4yeyHRjKsJe1X6AuaBxndxt3CEeyHmk+EoW+45CMF8+76+DlG+Xwtm2srpDP8SL6mrQQ3ssgeMU5jTGwPHf9KTRQkBXIbeojoSBBtvgIRE2pkXfs4QXbVzQ5SYHEIWcw0p45lHMRTkl4EBjJIrrocJD31j7lNcqnllj3238XQus2usZecFGWB6MkgYCx1kw1ib7zTZ3GgSjxCRZ/0NIvo6Afs52BPUQsg/uB6hJ3FiFJj6fT6nmT0ApUuZPudnKdsDpztzA2DCukky7r/gMeVg65R05ZiHODTZPnlJutG/ncrJX7zCSoFQzdjND/uDiO4ElYUJT3oy1Z/2slA8bR+b8utgg3YeRTt7FOQ1Zx78lsY/q6UHr47Ucj3Ng7zB7L9PLCNYyVuS4fjhOE2iLYiOxCGn68/Ac8oW1NkzVOZTTjXvGbYQEhxsP4uL5TzeTin3o68Lu/ZHo5Su1BVMTefPpJdx2n+f4cA==
  template:
    metadata:
      creationTimestamp: null
      name: headlamp-oidc-secret
      namespace: headlamp
    type: Opaque