---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: nutritrack
spec:
  encryptedData:
    AUTH_USER_PASSWORD: AgBqmUPtDc/GFomM1IiVoRWA+ZaH/FMFhsO3QphAcMqVXC/OpVl9Mz3HHay2nKCzfhaWVvZmV3BvGj1JTC6Kr2WZp0rkfAraZjvetrd7BqrAVel4QlSDs+gbf>
    COMPLIANCE_USER_PASSWORD: AgBjYsepKL4VyctIjCUYyC2fMABI0g+N/x7h6U6+GJcPp8FE9bH8hhby9icSkvCYN6GQ4A7r3zxxobObkQOBkIg0uSOmdjXF0GGIjEwfcNICyVGEgj3>
    FOOD_USER_PASSWORD: AgCD+ohEzmG+Kkc4oQGKLIzOlFMl3tjEwHW9sgrt6v9Q4miOXhuTFvJuKjuUExfGa42+Sl2KOxi8UzWPeDLZ2gm8lUHwoE3N/mE3qJwWJMYOXeQEEeLZkbFZy>
    MACRO_USER_PASSWORD: AgCWqYjG9j/NWZfGpiSwSxlD7c9/ttKUcQXCy5fg23epvRqTnb9Va2ACeGiVK708sqsBJ50Z5CMoBATjYEeRJQGUxrKFULNADYb+O+/0MqKMnG0WyrEriWt+>
    POSTGRES_PASSWORD: AgAtQAWN8XCDs6pE1md4cHayyQGkB3NMSG5UjWrDUz0aJiPi8kxzv6EPt249xS0iC0GOAPHrhSd+sxp7pI7CKDNnv1bbo2Kq2ntEtV2QtuhizoB59o/M2tbrNC>
    POSTGRES_USER: AgBDgiEKFMaw7Gl28kDAQOn5xVXyBAGNkfftrgJFbFXERAl28z0l9vkFzJWkp6g03ieK2wQit3ZcFdkJNUF377vPLNr7q2oeiCjwM9ogoceGJhEVKJZkJTPFrGgQer>
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: nutritrack
      name: postgresql-secret
      namespace: nutritrack
    type: Opaque