---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: compliance-service-secret
  namespace: nutritrack
spec:
  encryptedData:
    DATABASE_URL: AgBmSY9XE84NW9WBOLCIjvcMTrk2eKplZCu2QBPEjNH5BT7bPfN5HW7lfuj1vnNjYU4+seMv36VOzrFLHor5h86l9v8xqAZFCdTXjJ8PpksvrDaBYq5M2SNdz/dgdKkFLFzV/lVo3pYtbWK3w5Kwyr7CwTz4sL/uLtvfAe4FJQh0xOnhAvWk2i5aEQaUHpG6SAFfi3Muz97QTKueJ6Hnj7YRdhQJsZVdFQ0BF29csPCBFroB4nGIqnNupjKecJMTLzpWOjL1yuxBlfD6T7HrwCQAlHd9VXxOJ+CnC5AONn9+Ju1ZzsMN2zxw6oDhGp82ZOGQe/o6hERoomkGUJqjOgJl40ta516LoijAYAicdRxP5Eibroz//0V+MX0+umvnMR9XF/RtTfZGe6Q0cLCfpHEITLBqRPwYcd4VMnt6rpoHgAxKzGvqxrZVXg2ryyBgdbpvchtU/Ov6MdIBMr4irmCePgFCoJsmUy6oGz0npY6BPOfLUNgtapEhdRlgBFLQTcaRr76HYlkdTqQZXTia/ctrO4M4txB4WijGkT6cWTIWXkY9O22QXY9Z7dYZRo4Ue6exazBLQxBVNTtpF4+McabW0c/s9EXhBl6L81UF7ojdtJ/d3wMfaCIfGBWsU2HCRelVyGmHX7q+ykBqegOGb0dg3iaZTDHswWCc9hBjmvT6MnpdHbxjW+hyfRjXXLMPyU+f39JYsyIRGqEe1QR1/XcfgsHCpWxiJtqy1PuGQEyRLTNcyQ6mC53jtX2VHjYUOm/JIeOIz0TwchwXEYuXr29uSZil3NWXaL/Z5PtPz6erPKJ53yUQc+5v28X7wFrMZUIS89mz/OYJvuJSLmOF/eX8X41BLLassVMKS0JcmpkrgCjYDDSMsCL5ofs=
    JWT_SECRET: AgA/tI1SrlUvvNAujfjjTzFCV55Xn4Gv5lA0vqu4sIXl7cfszzIWQjHNZpvjh8mXyrltmfKatR8mWZMu/z9FcrLPQagsDawwcksZSra7woZcQxAYG24fjx6mLrN5Rz95p19VIx7tbUEvyzJxylVpEyOv8qMAnHq0c0R/vXf0Z17D3kjUYmQ/nOfhAXeQVnwdXpDQRDHCs9WGfFutPijf/I016Xnu3g5S+wJT6c+phDrBOSn9BqBUAvGqbOIR+5AV+HpRPtI7kvsCoEBMK7pj5Xtl+9BHp0u1Rg4SiuvcNQxFXQGXMZWGgW5gQDXOhEOyZMdp/5iNEPlPTfw8oWc3GIHDTnQkoRgyU1yTIZb/NZbB/G4BMc1k72E//BfHl3td8U0Hx5/KkMCOWPjV6TnUva/5iVT/2QOMrrS/D+aoR9ctMfYBFSkawVe+3UKUIzkbvM8JGiuEuoKeTZYQkWDRHR73ioAQ2ClYuLG/7Cvs6ZUgOuG4RdykgLWGEPjDyguncu3Z2+RL/3Kcxuq+hLUqwLzhtene7r3Uc9ctmwO40214DdTDkuwu1jJy7Go1/H9QO4oCFFShCHBrqi1N/AtH1A+IV0l4bV7QAOlofaOhRxMyje/CqqumBOBZbotp+ZIyFO8VdSzNJ8uTxG+2BkGCG/P/GHQXPkiRlpa6nymAhx8COJufPoBnZzJrNlVW0S85aCJ6VPQsyl2EsMrcJJbjgFfYQr0FJyr7ok/J5bHn+rbWetswr5qa8XIlZN5u8DRoQVhxeug=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: compliance-service
      name: compliance-service-secret
      namespace: nutritrack
    type: Opaque