---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: compliance-service-secret
  namespace: nutritrack
spec:
  encryptedData:
    DATABASE_URL: AgBmSY9XE84NW9WBOLCIjvcMTrk2eKplZCu2QBPEjNH5BT7bPfN5HW7lfuj1vnNjYU4+seMv36VOzrFLHor5h86l9v8xqAZFCdTXjJ8PpksvrDaBYq5M2SNdz/dgdKk>
    JWT_SECRET: AgA/tI1SrlUvvNAujfjjTzFCV55Xn4Gv5lA0vqu4sIXl7cfszzIWQjHNZpvjh8mXyrltmfKatR8mWZMu/z9FcrLPQagsDawwcksZSra7woZcQxAYG24fjx6mLrN5Rz95p>
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: compliance-service
      name: compliance-service-secret
      namespace: nutritrack
    type: Opaque
