---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: compliance-service-secret
  namespace: nutritrack
spec:
  encryptedData:
    DATABASE_URL: AgCnUBete54az8LZFjLyNZCgzoI5Wpmo10noldITcz42D/I4nMl1z0M59TuPF35+xt+jLSPSNSvNak2qnPFa4tRta9Ay33V4PdTLLgzIETVzO48dv8AfhIodGZcNv6eOBhi+zzSaHbKUgoZ4RsIqz0QNQ8GPoQksWa3O/lr0u6LvUOQro3t024f3EljMjbehC6L/B2n5MAE3lodlmulKCH/s+9ZC/sJowtm1H62Aq8sOWHmfAQscqg4JC97PKqG3yLLVyRmdQ5iBd2TTztqb5w7TRdAAcpS57ONEaF8e0vhep9Li/b7GDjftSgqdVaTWGQDGr7GeHQe2UIWHrzPrmNe+nDPrf4YkdCDZz8jddG6UKLxgJcCDSW0Nf6bPVZ690fplRZHYf2P8kc230+ytxSVm4s/QwA0lRJdJQeFbDB7T5b6czC0CxR9/u1k7MZllk1ndHAEUbIuxxEWDVLAPlIx/Kqu0nTkk06Nt50tEcHPXiCm6STpYXS84Vh7BJQBINAEZHlroMWjkh4n56ZIviNqVH4ZvcCquLdnuGai8WMICesySWpg4PR/z4EqzjIvrr5qMijJtdwDg470fs4Hlc1BtWaDL9HHzuJDw8pWjB4Y5jnuG2wbmaq21xGXZyyrWpO7hAE2P2L2UT5jQja89hTQ71gfPxrHQgqWDEcwRtLl1UEf8CjanX1BGx6wf2bXTr7Ec5WalqmU9ye2FGj8BEbFPpJuChHIONg8RXmfToOqI/dr/F/c/40lIqXXjGytKf2PquV2TVqCfdKRpzI/FHjXGm6DsSIz2iXKrjisJBu+t3ve5u0wF4SSaIQeDQsr7FYK+HIsVbE9U7d6MnjbIffWXOsQ0MmCmOANd3BCJsiz18unOfe+butj4Jgw=
    JWT_SECRET: AgCTAHv/mXUMocFRVEil8EmkAkbCxjIGUhffs35pmEV+Mg3eDG2rpMN5IAwPLvr1FgVyqQsQ1xwbsJl4yv95DUxRkvXfiFPvOqZx/9+mPxO53zNkZSNuelfy+b83Bg6ol9nB0mb/bw3DxW4O+0+/hqawGmVPcBh+nIPfwCE6vRlXGmoqgNegg8u7hLjZ39uiDBEdX5k+2UbF7gAgd04T5oIvy4v4ADnVmYw6tjOe5125WG6Np2ZpAchHE6xZl4k3yCwFvHsPOvkFHo4kxPiK2cBaho3v7HbkFtHjLunX6VqrCuFQ75tDzySTeuhho9M4Mt7QFIaNqQmyMHywglzFdSvG4k8OvTkxVieL6wFkLd6xZSW4GkbFYrWmK1nxNmFqXRi778cSYksrdiVAykP1Po7dO7cSiXUvEoQAU2MRpGdZdHMGtPWADUuRh8UgBQlxKb0ETcVqZEPLOSvOzDTlOoPI3omKyi0/Nbe2poAPFQCKbhmmfUjNaFkuxftwk52OT/kiO3Kv/isccpZtq/8KTY93ZEXvI02MOQ0gPJ9Bj+G6T7mwcHXjAt6WxIVX/DIEixAAE7Fk0OuYijTPrcOUTJ3s6vpIzDyq6eJwm1w3o/6ScaOBMSbUqNDhxWAOvjuhcFl7UQ1So8U7lE0wBS6NP/FpURDvqcX4mGmhWQAdvOWtBUyU8yorULcfMNTy888OrXtQZw7xFFnsAOLmtnjO+mjeqOTosvDq05mKchVbtdFsjGEataGZmlAq
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: compliance-service
      name: compliance-service-secret
      namespace: nutritrack
    type: Opaque
