---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-db-secret
  namespace: nutritrack-dev
spec:
  encryptedData:
    password: AgC4J0iBYNyJt0YRpr7qE1qsbzZNanUXUB+rGfOOdC0f7Q38qx4kM6A8ihHevvOWs33qG3uhuLkv5J/WZAJioWA8UNXIhXqg74A8XgNavYv3GgUboMD24COEn8v59Agg9BzAtqsdoithOHr0tZRLQJEoRFOLH03VQzj78aOP/dmNW3oeUDJJHPbLaXlAmelXXUC78hg2kXNtEEhwE4Depu8Lj8u0o84tR6TESctEaF+/14XtNFEFkZRYCYSfdSUZqUYp1OdBTalY0rOP3HmI3qtynKx2p7YKdW5NM9PjTvZmptyu522EoVTlzAvSW29mTSoU7hYlwkjoytmeBkb0kz3GBl6ec5dWYmC9o2YD6mX665elOTEV+kMvMb/tmtPkx2Syk+tuHS8uxR/mli7Hipv1YiaJgO2B9nwwBgdogLHWiN70XDqU/Zvb1mJaAgnSe7NVfRHPPxptX54hv9Np2nxNTr+1uG2AiQlZgpU5JrmtzerfwZoqdaKw7o4N0uSNZaNmHQnRxbExtPap2TX5ZK3nGEo+Y4U2Eggkq6zBaOo1Pl/wKsacymgi3NuRKIFdZz4CYEc1qx0S3v7o/3871J2mza9vR5XZEYcJnthYZK1TxoBOWEJqoSEv42K/HcB3C0wLp77G57X73l1kc71gS0voRxjIKDmqcizBLtCmcnDQ7QWhnookvhqi3dkUhFWk4e7ZwabSLdd81byj7ND1ClwS6ZHTZiR5E1TC
    username: AgCqzo8lujlSsocucz+V0FHZKSsEbADH/4Ub+zGvZKv3ovcaw7Lyczx7uBrEW28a71QBWpvlLEA4a7D++YL4bEeWbOE54D2Q35wExPClh4PNbJHV1AUbe9D+1rcsz2t6IGdcUUvT3LZhe/PvrIzLWtAI3PnkIpH3GTK0AhniZyU8TM/tVjM43dJUsNP6gQXydzFRx7zV/w1GNk+eoxaWNIcclI0dJO3M6ZH767qh55Q7i5j7fdJbvWVrwDaBnrcICRxn81FLRRsTSMnxS1SSyIZZLQFaT88SE/y7QtJw+ZJACeBEcINmSTAmEhXjEPH1u/ogpuEDOWocy4w8/kMJvM1OJVvRYi9+5U3SBSjaEx4DKSmOmSruW9Zh9FxBp86NP7OvDJvkeLpMMVnkJIN7evLZOfM5Kgl3gLTL0/tTj3s1tV0PvhuiO9NgcFSO7+/kU/ENWSkxO7a2rTYVzHikTbMCVMV7i5ZkZ+KcZr+8rOQ21vLvvD9cUwuAZS7YbQGnSu6DtnXHwgv/pZ9T9Ph//bAXSnq17xC/+h9YquxXcoEVCPOPjy0QBaqgGuekcj9AhMRAI5h3u6at+SvClhSCHyNXiKy7yTtftFlkKv52DwKxnc+2e8X9HYuqrSlXDnJlMYhBkNzoC48bl0mwYXJO1+UDB+rJNt1sAyP9I9PeUFVi/rPUL21lhHxRwAUiCiBCvkSepBhq4bkFyA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-db-secret
      namespace: nutritrack-dev
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin-secret
  namespace: nutritrack-dev
spec:
  encryptedData:
    password: AgCRl8QpLZjyPfG/8WcNvJiV3WdZs+MmHj+Kvkl82Fqzhlvso89RabWU9d8HWe081vbJ/wDGvResbpGfe7cxH7u2231wWDue8jaCGltL6czhPp+G+qIbE6j6s46IhX+kNpNnPh7pepAkMeyNzq/wIuc9Fqnq62kTucoI2QwoBXPuOa7oL1a+L84EvRzrHW31ZBiaiSxVhplP9sD3n3/d6xVh+b+gUaBUMmJtFkFAqUtawu0RVGXg6BovEuZF8984wLtt+2eZmwIp8X8Ll9kItcM1TfADZ5M3rp7RNEg02MPWNBwEXUqaHSzu5F1XG+7ZzLYT9TRz65k+aY7EVikQK9hjonnBqhR0RSDPqZKOuf/W5UN1nqW8qkTnMgmsuEhLRAi/vGdasN4vSKocE/5nZ2IGK+VGjmUevTB0u5Squ2TwHOC5XmQ+47CJZ3f1rbbGcZQZrk9KY0lZ+XmDffaFxj+zXdAz5YX/u7peWC9eHMZkIMC60Ht0v2koPK3OEayghiz/uyBvd1iYOvqOGXMYaHr/9aEwvB1JhLQVRhsEIDhbSGy96hwb069/F/NhnfkNp7MmjRpoU5v0OTUkwhTANbKjh/2CYm9jx34DpycdAFx5mYxzzsVqcu4EcWTQ6rxtvCRo7SXWgQZx/lUCLGe1kKBwsuR1B/hRtgl3A4zQs12lpQI3psVjpH5f2NBFcmSoEafNduC6LJXIq7LNvzY4DlVBV0KP6yw=
    username: AgCYRUFRocf41gzmnEZO42yyO9c8h/33egbbo3E4p6+XklgTYuQPoX96woCyC/oEtO/mOidlJZ8gYCCfZDAemjlTZg18YXNelOfxUNoCMzIV0u0grtqOqnDWc3bFR3+znIcUxiiKTVoUov/ALNgfzW2OBK0JsI77y1QQEOmxh1HNwpRyd7Ih8M9L1JRIUw8vQX7q/J3ARGiHFB/N4gVmj+4TGst3h341Aw2TLcQu6C9xTbOFikCBjDI10HP1HgCvMPdj6tffVo0/XQ/6+VSd02WJu3eNGnM2koqy0moi61bK3X4CXHPxkNnRApy9AqcE5skSt4DmuX6dizud25vP9KvPshbn7czVHgpZ+YizvV73hCcxVntoTSAQkJTC6J8NMj3Yn4gVnZV10IdAmnQwf2T+nNnim3or2dC6OVIeiDIE5zzNKyb8D+xYdHW6wkShx/7kybdlreoE17FIVKIX+amc1LHWYi1VtQsb1jI7cEQvkwcBjz81+4MeVQuMXChQLnCAZq5EX/tej1geoKoxFi3vvI7qI5loQ9aLhMVXcgNPrTzJxZSM3fmhUgUN66MDTqk3Ty3dL3lEp+oUbOl/y+q9+TWZ9hTNnm2rHI+VWzZH5IOpFliokSDoFspgYDxND2QT4ju0oG9fvvqZdS1AGCBFHBioGshZ5jelNwFIJG6hZiI1dpueNy8DqoFPQlRgwlcWpY5Gbw==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin-secret
      namespace: nutritrack-dev
    type: Opaque