apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: nutritrack
type: Opaque
stringData:
  # ⚠️  CHANGE THESE VALUES before deploying to production!
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "changeme-nutritrack-2026"
