apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nutritrack-auth-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: nutritrack
  source:
    repoURL: https://github.com/Nutri-Track/nutritrack-charts.git
    targetRevision: main
    path: microservices/auth-service
    helm:
      valueFiles:
        - ../../values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nutritrack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
