apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-bench
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: nutritrack
  source:
    repoURL: https://github.com/Nutri-Track/nutritrack-charts.git
    targetRevision: develop
    path: infrastructure/kube-bench
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
