---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-service-secret
  namespace: nutritrack
spec:
  encryptedData:
    DATABASE_URL: AgAaogvPsS8KBxfIgh2cNRvjCLPJZ5/+PFF8njuP2yxkk1Ly1CQxxm9ZqZci29PT2WT65SDCBB/p3QNcpF4+2d6ONKfOiynMJqfewF851Bun747Dqyi/+MvTagAeoYL
    JWT_SECRET: AgCL7gypcny4DyuewP9hoRRvIDjJ2WYHIu5A2AIyotuV1wO7ep1NHZ4CFFb1J6PYFNdHOUfX5VJMzCfZs2ymcSVTyynYBDiS5ogI08WJgep1FXPWkfIWb6JYn+26DfbrW
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-service
      name: auth-service-secret
      namespace: nutritrack
    type: Opaque
