---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-service-secret
  namespace: nutritrack
spec:
  encryptedData:
    DATABASE_URL: AgAaogvPsS8KBxfIgh2cNRvjCLPJZ5/+PFF8njuP2yxkk1Ly1CQxxm9ZqZci29PT2WT65SDCBB/p3QNcpF4+2d6ONKfOiynMJqfewF851Bun747Dqyi/+MvTagAeoYLIXXoF3RVK6N2AGowjr2Fz/9gNzj9Ql8nTBiEPA6YtGg3VvOXLIGvkY3ukTchkoZKTo2+V/FaThlXOZ0zwCh7Wi6lBNM8aKIMNsbOYIotTcpwD/kuMSSkp+w9EYiv9Tl3wTTq9E/Z6coOvqbl+ZJbVBYg2IX5Eyi2YiNqTv0oPrEFm91XWq/8823BWLUM36CFJ7+l6zCHHTsxMcHKiRxyacn+YTCDB6PDlEJy7k+Gde+gW4tzm6QoGYvSmjizYVehivjhskbSkoBu5Gr4nhpeCWtdVt04AlpSHKGV07IdXSR1fwp2tNUyiH0lFfnEVgr/skX6/DOHXg2Ot40BgtHYt7SozZqdd76SmuNwHeC/lD/rth1zqEouK4rV/eI4hchr4rCbneUvmZ02oX7lvy42g5lfKnl+cId3Zd/YzqlWWBZ4y4cfiLtudHUmUxg1+vcPGtTHRm0xBiNvMRInLiWS6LKEp5dS5+c4dlsWEzG1pDYuEAiTd4uZw7d025abvozwLGDmbfHg+5y0N0ADKb+JRSSsBsM391oKKxsYVEJtM2iD4vDNAVVBqP/HTkqHWbL5ZaeTxdhBCCQckx8fbrzTQ4evnd6OnOUPqJf6gzioOvGIfoOgAORUEHUW6ElgMo0ysjyXWAQ/ZI+zHRoruumboMWD6h26ltIaBfc0rGtx/7C4mNmXZb7aiB9cX6ZJ7gpp225L4zaWWNSkYzCiVpd2dCd/yyEEjhOzA4+A=
    JWT_SECRET: AgCL7gypcny4DyuewP9hoRRvIDjJ2WYHIu5A2AIyotuV1wO7ep1NHZ4CFFb1J6PYFNdHOUfX5VJMzCfZs2ymcSVTyynYBDiS5ogI08WJgep1FXPWkfIWb6JYn+26DfbrWR9YLBYS2OtQ+8vAjwixmnPKjhlWLbCReKa9YYPmX3svTcp8UkmIQZNyaFdGFHCk4MrDlMwTPW+jeLvpvtw6PV/q34jYDNXIR9NwEIEwdYJqMCyBbEYkC7KRPVYuNzdBSbtaIx6W+sKSlXDM2gneRfrEF8IFFotpJDQAeNHdTTv4d2hDJPIskSIB/iuZQyWZz7Ljy9apAt4BPSoLQLPt4K1ilKKAW2cwcasXghGnSIt4W9Mk9BHNc6uE/nhvTywicfOL7lw+Aan4nup9hiE1UNzrh4cs4LkxZPE4ME6Mny9dI7b3VkoRTN3DRHYMkTaSFzYmtN8YdsRI+Aa/gr3+TvXXdH4CSrvUWzRYca8U6n3/Um+sB3s0JdgUBHNQkvW/gd827EHRlx8ha5vj24pdKDC4SRQOkamSp5jd3V1oIdaqde2ZzPbxPClHx+pNAHpRxRfGycuKeMeNKAEGjRsjjFetX0ysMrLg0HdwQHpwRFFdW0DjIbkRwa7K8m5vDAT7inVbYbELtpTSvzjaBFSsziduZ3anx0P+e5LP8lPo25MfSIyV9svwPgkWq4yj4CyRTLQH/tOukS/IK9xfwN4DaV7+FAWdkHyCwNdXVdBLFJcSU+bhFaaau+dfitzRyFMVivAUMg4=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-service
      name: auth-service-secret
      namespace: nutritrack
    type: Opaque