---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-service-secret
  namespace: nutritrack
spec:
  encryptedData:
    DATABASE_URL: AgCy9vyt5RNyCq1owdJH2x8nSJL2YNVyXK/A0PB1NShELZ7gT0/j2nsGZvSRrghzOyCHIMs7daBCEjd6CPazdKxD64PiUpVWMba3anYfDGV+VLLAxNiYlSuj7VYoJtDWmE+cH+zHLXRv3l709PCa7gpP52jL7xf+ue/ly4iVqvJYcF45qv3rYylLejepyGH8o7665vnIu2EVgBmNwADxId8UOP1N82HsG55Uv4qLYoA33VZnhI8K5ROd8zNLTNmz8M3srSBTwO9fbSi2vegQVJ81LTbOJqy24azH0cKjLYAqs6GNet5hfrXsu38Q4Pbd8uwlU9NEn6r7lEMZ7zIwuzG28zBO2iKxoYbzoHqR+VcewNibj1gJsGGFz+Eh02HU+ElPL+ux/9IDXPDvEuAJdzSHn83CHCaer9LkCP02GnNmSJtt4lNXI1VmHNOvezgr/8/Q0WzELAznW0DoFF+wEbne+xTFunFNDHkZPWW2CmQtrKv2mLIGEZlSCm/v+7oC+7BBAV6RpZiVtR+LN/4U9wVqzt2Lvcjg2nUTDaW9ABv5eXxH5BAlwPVV2XAy9hR8tFaXZ/xRGRevFgz/S+Vp8X5Jzo2eeOUOhwUu6LMN1KHGYMChMiE7CZ0qb/6uzwSwDjeFOE0OAxDAU31kenYRFh80mULREZYyTH8+JYX7bd1I5ZYc5TSCjA4Isa6Iri9HZDXsXAIoiE6pqU0lzFee/RoDyUMIeJVZIpt7U5VXAIAoNCVEMuP6IomWH7Smh19lsaLAq4aRrnICgi/3sdBwbgSrvxL2CYAYOLh/B5eg+FhajWgTIYKZxZw3PWiYdkGRdmS+34x10u1Aw9sGLzVdLggxlgtxeEnHHbw=
    JWT_SECRET: AgBqDxyrn9pHxpP3h9R6MXmjrReMzLjZIF30q0BJCI51BTstInge3wDtHFaKmy4UREba6Tmx/OaH+YtO/l5cdUoI9XUZR+Cn/DIPie2DVXmo+yrpxdrKtJG80B09u5lnJPsuMwOjbc3NZgdgbjnSp4UOenua/m+WFsmYft+ojLam5gIXCS7+2thY/Unue29nWvRCcEEOxXePlLKUm7jvcxc/BeyzAkx4WYU+3BmzZekKWybK4LmOX/MVdPPV5KMKcEbM5fUTFbGkMc8uYODOqCvEJ8XwXnOlLdyKegPvOpdzsurG31ZBi9tSci+pkwQzFll/34sWwGQZypbjnbDvVN++R1QjOzcQFnrmtPZnZNiYBukmT+H6WcHqgES5odTL6UqQZQ8zRHrV6YSxBzUxWkyAiUuLRQKQfgYkqtYzUZYccHJjP85PH5htdmyUbWUYXvlZR1oW0mqzXO4m/l98G6A5Uqk7jQJFGSmHaBV2UkTBZ+/4yDaRkTBY4xgMO/GqFdBk5IPy0zWab7fJkV6eC3nXKJpe0xM744qu8CAZnHGZpNA7T7ALCQO75vOvlDUNMJF/siVW8K6n4Iy/5Uwb/w1hTK/6DPuNcdr6lhYCxIfNM/HFOsQcUmzLDV6FV6MUYPQwQNi71xxbF8+nlBitZfKtZES0ySvlFztPTyb3lmgc8vb3S3Z4lar2lqNTmvrTw6lhr8xzGIIWbno+Nymz1bneGTcc2KJ66vrIVvCJ4j5p64M2Z8nOfaSN
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-service
      name: auth-service-secret
      namespace: nutritrack
    type: Opaque
